package com.example.demo.Models;

import java.io.Serializable;
import java.util.Date;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "contractors") // Represents the contractors table in the database
@EntityListeners(AuditingEntityListener.class)
public class Contractor implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "contractor_id") // autogenerated primary key
    private Integer contractorId;

    @NotBlank // can't be empty
    @Column(nullable = false, columnDefinition = "VARCHAR(255)")
    private String name;

    @Column(name = "registration_number", columnDefinition = "VARCHAR(255)")
    private String registrationNumber;

    @Column(name = "country_code", length = 2)
    private String countryCode; // 2-character field storing the country abbreviation

    @CreatedDate // automatically sets this field to the current date and time when the a
                 // contractor was added
    @Column(name = "created_at", nullable = false, updatable = false)
    private Date createdAt;

    public Contractor() {
        super();
    }

    public Contractor(String name, String registrationNumber, String countryCode) {
        this.name = name;
        this.registrationNumber = registrationNumber;
        this.countryCode = countryCode;

    }

    public Integer getContractorId() {
        return contractorId;
    }

    public void setContractorId(Integer contractorId) {
        this.contractorId = contractorId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRegistrationNumber() {
        return registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Contractor [contractorId=" + contractorId + ", name=" + name
                + ", registrationNumber=" + registrationNumber + ", countryCode=" + countryCode
                + ", createdAt=" + createdAt + "]";
    }
}
